apiVersion: v1
kind: PersistentVolume
metadata:
  name: example-nfs-volume
spec:
  capacity:
    storage: 0.5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/pv
    server: ubuntu-xenial
    readOnly: false


